# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  default:
    - step:
        name: Defaults
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm run build
          - npm test
    - step:
        name: create artifact
        script:
          - mkdir artefacts
          - tar -czf artefacts/$HEROKU_APP_NAME-$BITBUCKET_BUILD_NUMBER.tar.gz --exclude=./artefacts .
          - cp artefacts/* .
        artifacts:
          - $HEROKU_APP_NAME-*.tar.gz
    - step:
        name: Deploy to production
        deployment: production
        script:
          - pipe: atlassian/heroku-deploy:1.0.1
            variables:
              HEROKU_API_KEY: $HEROKU_API_KEY
              HEROKU_APP_NAME: $HEROKU_APP_NAME
              ZIP_FILE: '$HEROKU_APP_NAME-$BITBUCKET_BUILD_NUMBER.tar.gz'
              WAIT: 'true' # Optional.
              DEBUG: 'true' # Optional
