# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm test
          - pipe: atlassian/heroku-deploy:1.1.0
                variables:
                    HEROKU_API_KEY: $HEROKU_API_KEY
                    HEROKU_APP_NAME: 'API Node JS'
                    ZIP_FILE: 'api-node-ipianetti-src.tar.gz'
