version: '3'
services:
  api-node-js:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      APP_PORT: $APP_PORT
      JWT_SECRET: $JWT_SECRET
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
    restart: unless-stopped
    ports:
      - $APP_PORT:$APP_PORT
    volumes:
      - ../.:/usr/src/app
