version: '3'
services:
  api-node-js:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      PORT: $PORT
      JWT_SECRET: $JWT_SECRET
      DB_URL: $DB_URL
      DB_AUTH_SOURCE: $DB_AUTH_SOURCE
    restart: unless-stopped
    ports:
      - $PORT:$PORT
    volumes:
      - ../.:/usr/src/app
